Finished API implementation and Base for CLI-Tool
smaxtec/sxapi pull request #52
Opened 2024-05-13 19:31 UTC by Mopsgeschwindigkeit

# Summary

This PR should be seen as a good base for further development. All Implemented features a working and are fully test (89% test coverage).

I have not verified it but i guess this branch cannot be merged into main without gigantic conflicts. Therefore i suggest, if the new design is to your liking, to use this branch as the new default.

For the foreseeable future I will stop working on this project, because of:

- Future of the public API not sure
- Company support is very little (which is completely understandable!)
- Currently I do not see someone using it. 

## API
This PR contains the complete implementation of every public API Endpoint provided via `PublicAPIv2` and `IntegrationAPIV2`. Located in `sxapi/src/<publicV2|integrationV2>`
## CLI
It also contains a basis for further CLI Tool implementations. Can be found under `sxapi/src/cli`.
There already some example Implementations for the CLI -> the animals, abort and token parser.

I did did full rebuild of the CLI design, thats why the approach is completely different from previous one.
The CLI now follows a `kubectl` style design, like

-  `sxapi animals get --ids <id1> <id2>` 
- `sxapi aborts delete <animal_id> <abort_id>`
- ...

2025-02-21 17:03 UTC, Mopsgeschwindigkeit commented
@flowolf updated the changed we talked about
- raise instead of return != 0
- better Error message for Sxapiauthorization Error
- fixed missing return (issue #53 )

2025-02-25 15:52 UTC, flowolf requested changes
thanks for the update. some small changes might be required

2025-02-25 15:52 UTC, flowolf commented on src/sxapi/cli/cli.py
> +        self.config_file_paths = []
not sure about this.

2025-02-25 15:52 UTC, flowolf commented on src/sxapi/cli/cli.py
> +            return
should this throw an exception?

2025-02-25 15:52 UTC, flowolf commented on src/sxapi/cli/cli.py
>              return
throwing an exception for missing input would be great here too.

2025-02-27 18:36 UTC, Mopsgeschwindigkeit commented on src/sxapi/cli/cli.py
> +        self.config_file_paths = []
mhm i assume the Outdated Label means you have reviewed an older commit.
I also cant find this code snipped in the lastest commit 🤔

2025-02-27 18:36 UTC, Mopsgeschwindigkeit commented on src/sxapi/cli/cli.py
> +            return
mhm i assume the Outdated Label means you have reviewed an older commit.
I also cant find this code snipped in the lastest commit 🤔

2025-02-27 18:37 UTC, Mopsgeschwindigkeit commented on src/sxapi/cli/cli.py
>              return
mhm i assume the Outdated Label means you have reviewed an older commit.
I also cant find this code snipped in the lastest commit 🤔

2025-11-23 10:08 UTC, merged